import streamlit as st
import random

# Title
st.title("PromptCanvas Lite")

# Dropdowns
theme = st.selectbox("Pick a theme:", [
    "Fantasy",
    "Science Fiction",
    "Dystopian",
    "Post-Apocalyptic",
    "Mystery",
    "Thriller",
    "Horror",
    "Psychological",
    "Romance",
    "Dark Romance",
    "Adventure",
    "Action",
    "Historical Fiction",
    "Supernatural",
    "Urban Fantasy",
    "Mythological",
    "Coming-of-Age",
    "Drama",
    "Crime",
    "Speculative Fiction"
])
mood = st.selectbox("Pick a mood:", ["Dark",
    "Bittersweet",
    "Chaotic",
    "Serene",
    "Gritty",
    "Dreamlike",
    "Lonely",
    "Uplifting",
    "Foreboding",
    "Intimate",
    "Violent",
    "Reflective"
])
character = st.selectbox("Pick a character:", [
    "Reluctant Hero",
    "Anti-Hero",
    "Tragic Villain",
    "Fallen Prodigy",
    "Quiet Genius",
    "Reckless Daredevil",
    "Loyal Best Friend",
    "Morally Grey Survivor",
    "Broken Warrior",
    "Cunning Strategist",
    "Naive Dreamer",
    "Haunted Outcast",
    "Charismatic Leader",
    "Cold Intellectual",
    "Hidden Monster",
    "Secret Royalty",
    "Rebellious Underdog",
    "Corrupted Idealist",
    "Protective Older Sibling",
    "Manipulative Mastermind",
    "Soft-Hearted Giant",
    "Ruthless Mercenary",
    "Idealistic Rookie",
    "World-Weary Veteran",
    "Masked Vigilante"
])

# Button to generate prompt
if st.button("Generate Prompt"):
    twists = [
    "with a secret they must hide.",
    "who discovers a mysterious object.",
    "facing an unexpected betrayal.",
    "that changes their life forever.",
    "who learns the truth too late.",
    "with a past they cannot escape.",
    "forced to choose between loyalty and survival.",
    "who realizes the enemy was right.",
    "hiding an identity no one would accept.",
    "who was never meant to exist.",
    "bound by a promise they regret.",
    "who unlocks an ability by accident.",
    "trapped in a lie that keeps growing.",
    "who becomes what they feared most.",
    "guided by a voice no one else hears.",
    "who remembers a future that hasn’t happened.",
    "forced to work with their rival.",
    "who loses something more valuable than life.",
    "with memories that don’t belong to them.",
    "who is being watched at all times.",
    "forced to repeat the same day.",
    "who learns they were the experiment.",
    "with a power that comes at a cost.",
    "who breaks the rules and survives.",
    "who was raised for a single purpose.",
    "forced to betray someone they love.",
    "who uncovers a forgotten truth.",
    "with a destiny they refuse to accept.",
    "who realizes the world is artificial.",
    "guided by someone who doesn’t exist.",
    "who was lied to about their origin.",
    "with a countdown they cannot stop.",
    "who sees what others cannot.",
    "forced into a role they hate.",
    "who learns the villain is family.",
    "with a choice that saves one life or many.",
    "who cannot trust their own memories.",
    "who wakes up somewhere impossible.",
    "forced to protect their enemy.",
    "who realizes they caused the disaster.",
    "with a power everyone wants.",
    "who is slowly losing themselves.",
    "bound to someone they despise.",
    "who learns the prophecy was fake.",
    "with a secret that could end everything.",
    "who survives when they shouldn’t have.",
    "forced to relive their worst mistake.",
    "who realizes they were manipulated.",
    "with an ability that only works once.",
    "who must lie to save the truth.",
    "who sees the consequences before actions.",
    "forced to abandon their name.",
    "who discovers they are replaceable.",
    "with a mark no one else can see.",
    "who is erased from history.",
    "forced to play a rigged game.",
    "who learns the hero is the villain.",
    "with a promise that cannot be broken.",
    "who finds out they were cloned.",
    "forced to lead despite fear.",
    "who realizes the threat is internal.",
    "with a power fueled by emotion.",
    "who hears thoughts they shouldn’t.",
    "forced to sacrifice their future.",
    "who uncovers a hidden society.",
    "with a truth that destroys relationships.",
    "who cannot die—but wishes they could.",
    "forced to wear a false identity.",
    "who learns their victory caused harm.",
    "with a gift that isolates them.",
    "who remembers being someone else.",
    "forced to choose who deserves saving.",
    "who realizes time is running out faster.",
    "with an ally who will betray them.",
    "who survives by breaking their morals.",
    "forced to confront their younger self.",
    "who learns their enemy was protecting them.",
    "with a power tied to pain.",
    "who uncovers a buried crime.",
    "forced to destroy what they built.",
    "who realizes they were never free.",
    "with a message meant for someone else.",
    "who becomes a symbol against their will.",
    "forced to trust the wrong person.",
    "who learns the rules can change.",
    "with a past that rewrites itself.",
    "who discovers the world ends soon.",
    "forced to give up their humanity.",
    "who realizes they are the final test.",
    "with a truth no one will believe.",
    "who wins but at a terrible cost.",
    "forced to walk away from everything.",
    "who learns some things should stay hidden.",
    "with a secret that protects others.",
    "who survives by becoming ruthless.",
    "forced to choose who they really are."
]

    twist = random.choice(twists)
    
    prompt = f"Write a {mood.lower()} {theme.lower()} story about a {character.lower()} {twist}"
    st.success(prompt)
